export const imageGallery = [
  {
    id: "1a2b3c",
    path: "/images/Cannot-redo-what-is-already-done.jpg",
    name: "Cannot redo what is already done",
    width: 1080,
    height: 1080,
    price: 149.99,
    category: "Surrealism",
  },
  {
    id: "4d5e6f",
    path: "/images/Doodies.jpg",
    name: "Doodies",
    width: 1080,
    height: 1080,
    price: 119.99,
    category: "Abstract",
  },
  {
    id: "7g8h9i",
    path: "/images/Fell-the-pain.jpg",
    name: "Fell the pain",
    width: 1080,
    height: 1080,
    price: 199.99,
    category: "Fantasy",
  },
  {
    id: "10j11k",
    path: "/images/Funk-and-vampires.jpg",
    name: "Funk and vampires",
    width: 1080,
    height: 1080,
    price: 179.99,
    category: "Surrealism",
  },
  {
    id: "12l13m",
    path: "/images/Inside-out.jpg",
    name: "Inside out",
    width: 1080,
    height: 1350,
    price: 159.99,
    category: "Abstract",
  },
  {
    id: "14n15o",
    path: "/images/Lost-in-the-dark.jpg",
    name: "Lost in the dark",
    width: 1080,
    height: 1296,
    price: 174.99,
    category: "Fantasy",
  },
  {
    id: "16p17q",
    path: "/images/Magic-archer.jpg",
    name: "Magic archer",
    width: 1080,
    height: 1080,
    price: 139.99,
    category: "Surrealism",
  },
  {
    id: "18r19s",
    path: "/images/Movie-night.jpg",
    name: "Movie night",
    width: 1080,
    height: 1080,
    price: 129.99,
    category: "Abstract",
  },
  {
    id: "20t21u",
    path: "/images/Old-scars.jpg",
    name: "Old scars",
    width: 1080,
    height: 1080,
    price: 154.99,
    category: "Fantasy",
  },
  {
    id: "22v23w",
    path: "/images/Pewpew-noises-in-the-background.jpg",
    name: "Pewpew noises in the background",
    width: 1080,
    height: 1080,
    price: 144.99,
    category: "Surrealism",
  },
  {
    id: "24x25y",
    path: "/images/Protected-by-the-sins.jpg",
    name: "Protected by the sins",
    width: 1080,
    height: 1080,
    price: 164.99,
    category: "Abstract",
  },
  {
    id: "26z27a",
    path: "/images/Red-room.jpg",
    name: "Red room",
    width: 1080,
    height: 1080,
    price: 174.99,
    category: "Fantasy",
  },
  {
    id: "28b29c",
    path: "/images/The-coffin-of Andy-and-Leyley.jpg",
    name: "The coffin of Andy and Leyley",
    width: 1080,
    height: 1080,
    price: 189.99,
    category: "Surrealism",
  },
  {
    id: "30d31e",
    path: "/images/The-separation-two-of-the-same.jpg",
    name: "The separation: two of the same",
    width: 1080,
    height: 1296,
    price: 199.99,
    category: "Abstract",
  },
  {
    id: "32f33g",
    path: "/images/Walk-in-the-park.jpg",
    name: "Walk in the park",
    width: 1080,
    height: 1080,
    price: 129.99,
    category: "Fantasy",
  },
];
