import {
  Disclosure,
  DisclosureButton,
  DisclosurePanel,
  Menu,
  MenuButton,
  MenuItem,
  MenuItems,
} from "@headlessui/react";
import { Bars3Icon, BellIcon, XMarkIcon } from "@heroicons/react/24/outline";

import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navigation = [
  { name: "Dashboard", href: "#", current: true },
  { name: "Team", href: "#", current: false },
  { name: "Projects", href: "#", current: false },
  { name: "Calendar", href: "#", current: false },
];

function classNames(...classes) {
  return classes.filter(Boolean).join(" ");
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Disclosure as="nav" className="bg-white">
          <div className="mx-auto max-w-7xl px-2 sm:px-10 lg:px-14">
            <div className="relative flex h-16 items-center justify-between">
              <div className="absolute inset-y-0 left-0 flex items-center sm:hidden">
                {/* Mobile menu button*/}
                <DisclosureButton className="group relative inline-flex items-center justify-center rounded-md p-2 text-gray-400 hover:bg-gray-700 hover:text-white focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white">
                  <span className="absolute -inset-0.5" />
                  <span className="sr-only">Open main menu</span>
                  <Bars3Icon
                    aria-hidden="true"
                    className="block h-6 w-6 group-data-[open]:hidden"
                  />
                  <XMarkIcon
                    aria-hidden="true"
                    className="hidden h-6 w-6 group-data-[open]:block"
                  />
                </DisclosureButton>
              </div>
              <div className="flex flex-1 items-center justify-center sm:items-stretch sm:justify-start">
                <div className="flex flex-shrink-0 items-center">
                  {/* <img
                    alt="Your Company"
                    src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=500"
                    className="h-8 w-auto"
                  /> */}

                  {/* <div className="h-8 w-auto"> */}
                  <svg
                    width="40"
                    height="40"
                    viewBox="0 0 57 56"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <line
                      x1="2.87868"
                      y1="27.8787"
                      x2="27.8787"
                      y2="2.87868"
                      stroke="#B80000"
                      stroke-width="6"
                    />
                    <line
                      x1="10.581"
                      y1="22.3384"
                      x2="41.6294"
                      y2="53.3867"
                      stroke="#B80000"
                      stroke-width="6"
                    />
                    <line
                      x1="31.5598"
                      y1="30.4374"
                      x2="54.5598"
                      y2="44.4374"
                      stroke="#B80000"
                      stroke-width="6"
                    />
                    <path
                      d="M26.4693 17.8284C28.0314 16.2663 30.5641 16.2663 32.1262 17.8284L35.1716 20.8739C36.7337 22.436 36.7337 24.9686 35.1716 26.5307L25.0208 36.6815L16.3185 27.9793L26.4693 17.8284Z"
                      stroke="#B80000"
                      stroke-width="6"
                    />
                    <path
                      d="M10 3H46C49.866 3 53 6.13401 53 10V46C53 49.866 49.866 53 46 53H10C6.13401 53 3 49.866 3 46V10C3 6.13401 6.13401 3 10 3Z"
                      stroke="#B80000"
                      stroke-width="6"
                    />
                  </svg>
                  {/* </div> */}
                </div>
                <div className="hidden sm:ml-6 sm:block">
                  <div className="flex space-x-4">
                    {navigation.map((item) => (
                      <a
                        key={item.name}
                        href={item.href}
                        aria-current={item.current ? "page" : undefined}
                        className={classNames(
                          item.current
                            ? "bg-gray-600 text-white"
                            : "text-black hover:bg-gray-600 hover:text-white",
                          "rounded-md px-3 py-2 text-sm font-medium duration-300"
                        )}
                      >
                        {item.name}
                      </a>
                    ))}
                  </div>
                </div>
              </div>
              <div className="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">
                <div className="pr-2">
                <button
                  type="button"
                  className="relative rounded-full bg-white p-1 text-black focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800"
                >
                  <span className="absolute -inset-1.5" />
                  <span className="sr-only">View notifications</span>
                  <BellIcon aria-hidden="true" className="h-6 w-6" />
                </button>
                </div>

                <div>
                  <a
                    href={"#"}
                    // aria-current={item.current ? "page" : undefined}
                    className={
                      "text-black border border-current hover:bg-gray-600 hover:text-white rounded-md px-3 py-2 text-sm font-medium duration-300"
                    }
                  >
                    Login
                  </a>
                </div>

                <div className="pl-2 hidden md:block">
                  <a
                    href={"#"}
                    // aria-current={item.current ? "page" : undefined}
                    className={
                      "text-white bg-gray-600 hover:bg-gray-600 hover:text-white hover:bg-gray-900 rounded-md px-3 py-2 text-sm font-medium duration-300"
                    }
                  >
                    Register
                  </a>
                </div>

                {/* Profile dropdown */}
                {/* <Menu as="div" className="relative ml-3">
                  <div>
                    <MenuButton className="relative flex rounded-full bg-gray-800 text-sm focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800">
                      <span className="absolute -inset-1.5" />
                      <span className="sr-only">Open user menu</span>
                      <img
                        alt=""
                        src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                        className="h-8 w-8 rounded-full"
                      />
                    </MenuButton>
                  </div>
                  <MenuItems
                    transition
                    className="absolute right-0 z-10 mt-2 w-48 origin-top-right rounded-md bg-white py-1 shadow-lg ring-1 ring-black ring-opacity-5 transition focus:outline-none data-[closed]:scale-95 data-[closed]:transform data-[closed]:opacity-0 data-[enter]:duration-100 data-[leave]:duration-75 data-[enter]:ease-out data-[leave]:ease-in"
                  >
                    <MenuItem>
                      <a
                        href="#"
                        className="block px-4 py-2 text-sm text-gray-700 data-[focus]:bg-gray-100"
                      >
                        Your Profile
                      </a>
                    </MenuItem>
                    <MenuItem>
                      <a
                        href="#"
                        className="block px-4 py-2 text-sm text-gray-700 data-[focus]:bg-gray-100"
                      >
                        Settings
                      </a>
                    </MenuItem>
                    <MenuItem>
                      <a
                        href="#"
                        className="block px-4 py-2 text-sm text-gray-700 data-[focus]:bg-gray-100"
                      >
                        Sign out
                      </a>
                    </MenuItem>
                  </MenuItems>
                </Menu> */}
              </div>
            </div>
          </div>

          <DisclosurePanel className="sm:hidden">
            <div className="space-y-1 px-2 pb-3 pt-2">
              {navigation.map((item) => (
                <DisclosureButton
                  key={item.name}
                  as="a"
                  href={item.href}
                  aria-current={item.current ? "page" : undefined}
                  className={classNames(
                    item.current
                      ? "bg-gray-900 text-white"
                      : "text-gray-300 hover:bg-gray-700 hover:text-white",
                    "block rounded-md px-3 py-2 text-base font-medium"
                  )}
                >
                  {item.name}
                </DisclosureButton>
              ))}
            </div>
          </DisclosurePanel>
        </Disclosure>
        {children}
      </body>
    </html>
  );
}
